export const metadata = {
    title: 'Profile | Next Hero',
    description: 'Generated by create next app',
}
const ProfilePage = () => {
    return (
        <div>
            <h1>Welcome to my profile</h1>
        </div>
    );
};

export default ProfilePage;