export const metadata = {
    title: 'About | Next Hero',
    description: 'Generated by create next app',
}
const AboutPage = () => {
    return (
        <div>
            This is about AboutPage
        </div>
    );
};

export default AboutPage;