
import Link from "next/link";
export const metadata = {
    title: 'Blogs | Next Hero',
    description: 'Generated by create next app',
}

const blogsItem = [
    {
        id: 1,
        year: 2023,
        title: "title 1",
    },
    {
        id: 2,
        year: 2023,
        title: "title 2",
    },
    {
        id: 3,
        year: 2023,
        title: "title 3",
    },
    {
        id: 4,
        year: 2023,
        title: "title 4",
    },
]
const BlogsPage = () => {
    return (
        <div>
            <h1 className="my-2">This is blog page and total blog: {blogsItem.length}</h1>
            {
                blogsItem.map(({ id, year, title }) => (
                        <div className="border border-blue-800 mb-2 p-3" key={id}>
                            <h1>{title}</h1>
                            <Link href={{
                                pathname: `/blog/${year}/${id}`,
                                query: {
                                    title: title
                                }
                            }} className="btn bg-blue-400 text-white p-2 inline-block">Details</Link>
                        </div>
                    )
                )
            }
        </div>
    );
};

export default BlogsPage;