export const metadata = {
    title: 'Dashboard | Add-product | Next Hero',
    description: 'Generated by create next app',
}
const AddProductPage = () => {
    return (
        <div>
            <p className="text-xl text-slate-800">Product List</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Magnam dignissimos quaerat, minus modi nobis consequatur in magni cupiditate veniam laboriosam, voluptatibus, recusandae explicabo totam voluptatem aspernatur reiciendis vero? Est, at?</p>
        </div>
    );
};

export default AddProductPage;