import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Hero',
  description: 'Generated by create next app',
}

const RootLayout=({ children })=> {
  return (
    <html lang="en">
      <body className='max-w-7xl m-auto p-3'>
          {children}
      </body>
    </html>
  )
}
export default RootLayout;
