import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout=({ children })=> {
  return (
    <html lang="en">
      <body>
        <div>Header menu</div>
          {children}
        <div>Footer section</div>
      </body>
    </html>
  )
}
export default RootLayout;
