export const metadata = {
    title: 'Dashboard | Manage-product | Next Hero',
    description: 'Generated by create next app',
}
const ManageProduct = () => {
    return (
        <div>
            <p>Product will be manage </p>
        </div>
    );
};

export default ManageProduct;