import getAllproducts from "@/app/utils/getAllproducts";
import ManageProducts from "../../components/Dashboard/ManageProducts";

export const metadata = {
    title: 'Dashboard | Manage-product | Next Hero',
    description: 'Generated by create next app',
}
const ManageProduct = async () => {
    const products = await getAllproducts();
    return (
        <div className="w-full">
            <p className="text-xl font-semibold mb-2">All Products List </p>
            <ManageProducts products={products}/>
        </div>
    );
};

export default ManageProduct;