export const metadata = {
    title: 'Profile | Next Hero',
    description: 'Generated by create next app',
}
const ProfilePage = () => {
    return (
        <div>
            <h1 className="text-rose-600">This is profile page </h1>
        </div>
    );
};

export default ProfilePage;