import Sidebar from "./Sidebar";

export const metadata = {
    title: 'Dashboard | Next Hero',
    description: 'Generated by create next app',
}
const DashboardLayout = ({ children }) => {
    return (
        <div className="flex gap-8 ">
            <Sidebar></Sidebar>
            {children}
        </div>
    );
};

export default DashboardLayout;