import Link from "next/link";

export const metadata = {
    title: 'Dashboard | Next Hero',
    description: 'Generated by create next app',
}
const DashboardLayout = ({ children }) => {
    return (
        <div>
            <div className="flex gap-2">
                <Link href="/" className="rounded-lg border-[2px] border-slate-900 px-3 py-1">sidebar</Link>
                <Link href="/" className="rounded-lg border-[2px] border-slate-900 p-2">Home</Link>
            </div>
            {children}
        </div>
    );
};

export default DashboardLayout;