export const metadata = {
    title: 'Dashboard | Next Hero',
    description: 'Generated by create next app',
}
const DashboardLayout = ({children}) => {
    return (
        <div>
            sidebar
            {children}
        </div>
    );
};

export default DashboardLayout;